crate/crate-dbal

- LICENSE
The year in the license file needed to be updated to include 2015
> Update year in copyright license: Trello #693

- README.rst
I flagged the same issue in the pdo driver (https://github.com/crate/crate-pdo/pull/25) telling users to use an old version causes errors when running `composer install`, changing instructions to use the latest version clears these problems.
> Version update to docs

- composer.json
running `composer validate` resulted in a warning about an invalid license identifier.
> fixes license identifier according to https://spdx.org/licenses/

- provisioning.sh
adds composer and php dependencies installation to vagrant provisioning
- install packages `git`,`zip` and `upzip` required by `composer`.
- install latest `composer` binary into global path.
vagrant: install `doctrine/dbal` dependency from source.
The distribution of `doctrine/dbal` is missing the required
test base classes `crate-dbal` is relying on.
> fixes phpunit test runs inside vagrant

- composer.json
- test/Crate/Test/DBAL/Platforms/CratePlatformTest.php
... so that `crate-dbal` can be used with PHP Symfony which requires dbal >= 2.6
> Bump doctrine/dbal dependency to 2.6.3

- CHANGES.txt
- composer.json
- docs/appendices/index.rst
- docs/appendices/table-options.rst
- docs/buildout.cfg
- docs/versions.cfg
- src/Crate/DBAL/Platforms/CratePlatform.php
- test/Crate/Test/DBAL/Functional/TableOptionsTest.php
CrateDB supports some specific table options e.g. for configuring
sharding, partitioned tables or number of replicas.
Passing this configurations via DBAL `$options` is now possible.
Relates #75.
> Add support for CrateDB specific table options

- CHANGES.txt
- src/Crate/DBAL/Platforms/CratePlatform.php
- src/Crate/DBAL/Platforms/CratePlatform1.php
- src/Crate/DBAL/Schema/CrateSchemaManager.php
- test/Crate/Test/DBAL/Functional/Schema/SchemaManagerTest.php
The SchemaManager raised an exception while reading tables *without*
any PRIMARY KEY constraints and ignored them when existing.
Relates #75.
> Fix handling of PRIMARY KEY constraints 

- CHANGES.txt
- composer.json
- test/Crate/Test/DBAL/DBALFunctionalTestCase.php
- test/Crate/Test/DBAL/Functional/ConnectionTest.php
- test/Crate/Test/DBAL/Functional/DataAccessTest.php
- test/Crate/Test/DBAL/Functional/ModifyLimitQueryTest.php
- test/Crate/Test/DBAL/Functional/NamedParametersTest.php
- test/Crate/Test/DBAL/Functional/Schema/SchemaManagerTest.php
- test/Crate/Test/DBAL/Functional/TypeConversionTest.php
- test/Crate/Test/DBAL/Functional/WriteTest.php
- test/Crate/Test/DBAL/Platforms/CratePlatformTest.php
upgrade dbal to 2.10
upgrade phpunit to 8.0.0 because of missing method
Mockbuilder->addMethods was added in Phpunit 8.
Doctrine AbstractPlatform is using this method
closes #80
> upgrade dbal to 2.10

- test/Crate/Test/DBAL/Functional/DataAccessTest.php
- test/Crate/Test/DBAL/Functional/ModifyLimitQueryTest.php
Since DBAL 2.10, $conn->quote is using the driver’s connection->quote
correctly but Crate-PDO does not support quoting of strings by intent.
The other failing test was flaky cause of a missing ordering clause.
> Fix tests related to dbal 2.10 and flaky ordering

- CHANGES.txt
- docs/connect.rst
- src/Crate/DBAL/Platforms/CratePlatform.php
- src/Crate/DBAL/Schema/CrateSchemaManager.php
- test/Crate/Test/DBAL/Functional/TableOptionsTest.php
This should address #84.
When using ``getOptions()`` with a Table that was retrieved from the schema manager, the driver will now load the Table's options, such as sharding and partition information.
```
<?php
use Doctrine\DBAL\Schema\Table;
$params = array(
'driverClass' => 'Crate\DBAL\Driver\PDOCrate\Driver',
'user' => 'crate',
'host' => 'localhost',
'port' => 4200
);
$connection = \Doctrine\DBAL\DriverManager::getConnection($params);
$schemaManager = $connection->getSchemaManager();
$platform = $connection->getDatabasePlatform();
$options = [];
$options['sharding_routing_column'] = 'id';
$options['sharding_num_shards'] = 6;
$options['partition_columns'] = ['parted', 'date'];
$options['table_options'] = [];
$options['table_options']['number_of_replicas'] = '0-2'; …
```
> Implement list table details to include specific CrateDB table options

- CHANGES.txt
- docs/getting-started.rst
- src/Crate/DBAL/Driver/PDOCrate/Driver.php
@seut I suppose this would count as a Change and not a Fix, since the behaviour wasn't necessarily a bug before? So it should be 2.3.0, not 2.2.1?
> Prepare release 2.3.0

- composer.json
The test build failed cause the current dbal versioning allowed
to use doctrine-dbal 2.10.x which has breaking test suite changes.
Supersedes #90.
> Pin doctrine-dbal to v2.9.x to avoid any breaking changes

- .github/workflows/tests.yml
- CONTRIBUTING.rst
- README.rst
- docs/appendices/data-types.rst
This patch accompanies the adjustment of the main branch of this repository to be now called "main".
> Rename default branch to "main"

- .github/workflows/tests.yml
- .scrutinizer.yml
- README.rst
- GHA: Submit code coverage reports only once
- Scrutinizer CI: Allow more time for waiting on code coverage reports
> CI: Slightly adjust GHA and Scrutinizer configuration settings

- .github/workflows/tests.yml
- .scrutinizer.yml
This patch tries to improve the behavior on CI.
1. Fix GHA dependency caching
2. Scrutinizer yelled
```
+==================================================================================+
| PHP Copy/Paste Detector and PHP Code Similarity Analyzer cannot both be used at |
| the same time. Please remove either one, f.e. by adding 'php_cpd: false'.       |
+=================================================================================+
```
Background: There is a new (2014 already, see [1]) Code Similarity Analyzer we are switching to now.
> In PHP, Copy/Paste Detector so far could be used for detecting code clones. On Scrutinizer, it was enabled by default on all PHP projects. PHP Copy/Paste Detector operates on the token stream which is generated by PHP’s token_get_all function and uses …
> CI: Disable Copy/Paste Detector in favor of Code Similarity Analyzer

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- .scrutinizer.yml
- DEVELOP.rst
- README.rst
- codecov.yml
- composer.json
- docs/Makefile
- docs/appendices/compatibility.rst
- docs/appendices/data-types.rst
- docs/build.json
- docs/getting-started.rst
Hi,
this is a mixture of things I still had on my working tree paired with some updates similar to https://github.com/crate/crate-pdo/pull/118 and https://github.com/crate/crate-pdo/pull/119.
- Update to crate-docs 2.0.0
- Run link checker each morning
- Update some outdated links
- Use Codecov instead of Coveralls
- Update Scrutinizer configuration
- Improve README and DEVELOP documents
- Remove notes about "enterprise edition" from documentation
With kind regards,
Andreas.
> Update and fix environment and documentation

- .github/workflows/docs.yml
- .scrutinizer.yml
- AUTHORS.rst
- CHANGES.txt
Hi,
this patch bundles three small updates.
- CI: Don't run docs building on GHA/macOS, it is dead slow
- CI: Don't let Scrutinizer expect two coverage runs
- Update changelog re. #113
With kind regards,
Andreas.
> Some adjustments, mostly CI

- .github/workflows/tests.yml
Hi.
After the [recent security event at Codecov](https://about.codecov.io/security-update/), they started rolling out their new uploader, see [1]. According to their deprecation plan, they are already conducting scheduled brownouts of the Bash Uploader, starting Sept 1, 2021.
As we are using the corresponding GitHub Action here, see also [2] for further deprecation notices and migration notes.
With kind regards,
Andreas.
[1] https://about.codecov.io/blog/introducing-codecovs-new-uploader/
[2] https://github.com/marketplace/actions/codecov
> Use new Codecov uploader instead of the Bash Uploader

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- .scrutinizer.yml
- CHANGES.txt
- README.rst
- composer.json
Hi there,
mainly intended to add support for PHP8.1 and PHP8.2, there are also a few other maintenance commits. See also https://github.com/crate/crate-pdo/pull/132.
- https://php.watch/versions/8.1
- https://php.watch/versions/8.2
With kind regards,
Andreas.
> CI: Add support for PHP8.1 and PHP8.2, and update GHA recipe versions

- CHANGES.txt
- src/Crate/DBAL/Driver/PDOCrate/Driver.php
Publishing a patch release which allows installation on PHP8.1 and PHP8.2. See also https://github.com/crate/crate-pdo/pull/134.
> Release 3.0.1

- .github/workflows/tests.yml
- CHANGES.txt
- composer.json
Drop support for PHP 7.x, it is EOL. See https://www.php.net/supported-versions.php.
Firstly, an unqualified / trial-and-error attempt to resolve GH-128.
Now, the outcome also relates to https://github.com/crate/crate-pdo/pull/152.
> Drop support for PHP 7.x

- DEVELOP.rst
The last release was slightly bumpy. This patch adds a documentation section about how to do it properly.
- https://packagist.org/packages/crate/crate-dbal
> Chore: Add documentation section about how to release the package

- docs/appendices/compatibility.rst
- docs/appendices/data-types.rst
- docs/connect.rst
- docs/index.rst
This patch fixes a few broken links, which blocks CI runs on GH-133 and GH-134.
> Chore: Fix broken links. Old DBAL docs are no longer available, use 3.0.

- .github/workflows/tests.yml
- CHANGES.txt
- README.rst
- composer.json
PHP 8.4 has been released on Nov 21, 2024.
- https://www.php.net/releases/8.4/
> Verify support on PHP 8.4

- docs/appendices/compatibility.rst
- docs/appendices/index.rst
- docs/connect.rst
- docs/getting-started.rst
- docs/index.rst
Remove redundant page-local TOC.
Part of  https://github.com/crate/tech-content/issues/140
https://crate-dbal--138.org.readthedocs.build/en/138/
> remove page-local TOC
